dataset: kvasir
nclass: 2
crop_size: 256
data_root: /home/wth/My_codes/SSL_MIS_Exps/polyp
# arguments for training
epochs: 3000
batch_size: 8 # per GPU x 1 GPU
lr: 0.01
conf_thresh: 0.95

conf_thresh_high: 0.95
conf_thresh_low: 0.85